### ISSUE TITLE
Login and registration Forms

### ISSUE THREAD

**Issue by Harryonismyname** [DaddyO93/storeFront#16]
As of right now, the modals for login and registration refresh the page, when they send the data across the POST route. We could remove that page refresh by using ajax to update the session without reloading the page. Unless the login is going to lead to a different side of the server.

**Comment by russlance** [comment]
I was just thinking about that. What if when an admin logs in it automatically moves him to admin_home? From there an admin can always go back to the store side, but most of the time an admin will need to be on the admin side anyway. 

If a standard user logs in I would not have it refresh/reload the page because they might lose their progress or shopping cart.
